### ISSUE TITLE
How can I find the defination of “Average Precision”

### ISSUE THREAD

**Issue by li-zemin** [rohitgirdhar/GenerativePredictableVoxels#8]
Hello, thanks for your sharing and excellent work. In your paper, you tested your model over IKEA dataset and scored with "average precison" to represent the reconstruction ability of your trained model. And this critic is cited by several papers successively. However, there is no specific defination of Average Precision. 
Could you provide the defination of "Average Precision" for me? Thank you!

**Comment by rohitgirdhar** [comment]
AP is used to evaluate our approach because we produce a confidence value for each voxel. Hence, for any given confidence threshold, we can compute: 1) Precision: Of all the voxels we predict as occupied, how many were actually occupied in the ground truth; and 2) Recall: How many of GT occupied voxels were we able to predict as occupied. AP essentially computes the P-R curve at multiple thresholds, and returns the area under that curve. In practice, we used the standard [scipy AP function](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html).

**Comment by li-zemin** [comment]
Thanks very much, I will have a test.
